[package]
name = "demo-lib"
version = "0.1.0"
authors = ["Yan QiDong <yanqd0@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "demo"

[dependencies]
