[package]
name = "demo-py"
version = "0.1.0"
edition = "2018"

[lib]
name = "demo_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.1", features = ["extension-module"] }
demo-lib = { path = '../demo-lib' }
